[[headers]]
  for = "/.well-known/apple-app-site-association"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "max-age=0, no-cache, no-store, must-revalidate"

[[headers]]
  for = "/apple-app-site-association"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "max-age=0, no-cache, no-store, must-revalidate"